// Initial data for НЦ "Защитные и функциональные покрытия"
// Auto-generated from TasksPROFCOAT.xlsx and Команда/Проекты

window.PEOPLE_DICT = {
  "ZarinaA": "Арингожина Зарина Ержановна",
  "ArystanbekK": "Кусайнов Арыстанбек Ерланович",
  "AinurS": "Серікбайқызы Айнұр",
  "IndiraA": "Абижанова Индира Кенжебековна",
  "YermakhanM": "Молбосынов Ермахан Серікұлы",
  "ArnurA": "Асхатов Арнур Нуржанович",
  "AsemK": "Кочнева Асем",
  "GulnaraZh": "Жунісова Гульнара Жунісқызы",
  "MoldirK": "Қалиаскарова Мөлдір Төлеуханқызы",
  "RauanB": "Болатбек Рауан",
  "NurasylZh": "Жасуланұлы Нұрасыл",
  "YelamanB": "Батанов Еламан Ермекұлы",
  "AidarK": "Кеңесбеков Айдар Бақытбекұлы",
  "NurtoleuM": "Магазов Нуртолеу Магзумбекович"
};

window.EMPLOYEES_INITIAL = [
  {
    "id": "AidarK",
    "fullName": "Кеңесбеков Айдар Бақытбекұлы",
    "shortName": "AidarK",
    "dob": "1994-04-13",
    "position": "PhD",
    "emailPersonal": "kenesbekovaidar@gmail.com",
    "emailWork": "akenesbekov@edu.ektu.kz",
    "phone": "+7 777 245 20 66",
    "scopusId": "57205287682",
    "wosId": "AAJ-2006-2021",
    "orcid": "0000-0002-5630-9467"
  },
  {
    "id": "NurtoleuM",
    "fullName": "Магазов Нуртолеу Магзумбекович",
    "shortName": "NurtoleuM",
    "dob": "1999-05-08",
    "position": "PhD st",
    "emailPersonal": "magazovn@mail.ru",
    "emailWork": "nmagazov@edu.ektu.kz",
    "phone": "+7 747 426 30 19",
    "scopusId": "57220041350",
    "wosId": "ADJ-9528-2022",
    "orcid": "0000-0002-9941-9199"
  },
  {
    "id": "ZarinaA",
    "fullName": "Арингожина Зарина Ержановна",
    "shortName": "ZarinaA",
    "dob": "1989-04-03",
    "position": "PhD",
    "emailPersonal": "zaringozhina@gmail.com",
    "emailWork": "zaringozhina@edu.ektu.kz",
    "phone": "+7 705 417 89 29",
    "scopusId": "58639928600",
    "wosId": "IXL-4677-2023",
    "orcid": "0009-0001-8428-4033"
  },
  {
    "id": "ArystanbekK",
    "fullName": "Кусайнов Арыстанбек Ерланович",
    "shortName": "ArystanbekK",
    "dob": "2000-11-28",
    "position": "PhD st",
    "emailPersonal": "arys20055@gmail.com",
    "emailWork": "",
    "phone": "+7 707 783 70 60",
    "scopusId": "59065558000",
    "wosId": "",
    "orcid": "0000-0003-4623-4681"
  },
  {
    "id": "AinurS",
    "fullName": "Серікбайқызы Айнұр",
    "shortName": "AinurS",
    "dob": "1995-05-01",
    "position": "PhD st",
    "emailPersonal": "a.s-01@bk.ru",
    "emailWork": "ainura.serikbaikyzy@gmail.com",
    "phone": "+7 776 125 94 39",
    "scopusId": "",
    "wosId": "LRT-7969-2024",
    "orcid": "0009-0005-7734-9512"
  },
  {
    "id": "IndiraA",
    "fullName": "Абижанова Индира Кенжебековна",
    "shortName": "IndiraA",
    "dob": "1997-02-12",
    "position": "PhD st",
    "emailPersonal": "iabizhanova@gmail.com",
    "emailWork": "IAbizhanova@edu.ektu.kz",
    "phone": "+7 771 179 79 37",
    "scopusId": "",
    "wosId": "ADR-8182-2022",
    "orcid": "0009-0006-3218-7246"
  },
  {
    "id": "AsemK",
    "fullName": "Кочнева Асем",
    "shortName": "AsemK",
    "dob": "1986-04-03",
    "position": "PhD st",
    "emailPersonal": "asem_kumarovna_kochneva@mail.ru",
    "emailWork": "",
    "phone": "+7 705 197 70 00",
    "scopusId": "",
    "wosId": "",
    "orcid": ""
  },
  {
    "id": "GulnaraZh",
    "fullName": "Жунісова Гульнара Жунісқызы",
    "shortName": "GulnaraZh",
    "dob": "1996-11-03",
    "position": "MS",
    "emailPersonal": "junusova6@gmail.com",
    "emailWork": "GZhunisova@edu.ektu.kz",
    "phone": "+7 747 776 48 86",
    "scopusId": "",
    "wosId": "",
    "orcid": "0009-0008-2277-6666"
  },
  {
    "id": "YelamanB",
    "fullName": "Батанов Еламан Ермекұлы",
    "shortName": "YelamanB",
    "dob": "2002-02-08",
    "position": "M st",
    "emailPersonal": "batanovelman1234@gmail.com",
    "emailWork": "",
    "phone": "+7 708 750 94 36",
    "scopusId": "",
    "wosId": "",
    "orcid": "0009-0003-2593-6665"
  },
  {
    "id": "MoldirK",
    "fullName": "Қалиаскарова Мөлдір Төлеуханқызы",
    "shortName": "MoldirK",
    "dob": "2003-10-09",
    "position": "M st",
    "emailPersonal": "kaliaskarovaa.01@gmail.com",
    "emailWork": "mkaliaskarova@edu.ektu.kz",
    "phone": "+7 747 848 82 71",
    "scopusId": "",
    "wosId": "",
    "orcid": "0009-0003-4743-3284"
  },
  {
    "id": "YermakhanM",
    "fullName": "Молбосынов Ермахан Серікұлы",
    "shortName": "YermakhanM",
    "dob": "2004-02-14",
    "position": "B st",
    "emailPersonal": "mr.molbosunov@gmail.com",
    "emailWork": "molbossynov.ye@edu.ektu.kz",
    "phone": "+7 777 155 99 04",
    "scopusId": "59345086000",
    "wosId": "OSI-7704-2025",
    "orcid": "0009-0009-0578-6544"
  },
  {
    "id": "ArnurA",
    "fullName": "Асхатов Арнур Нуржанович",
    "shortName": "ArnurA",
    "dob": "2003-11-29",
    "position": "B st",
    "emailPersonal": "ashatovarnur@gmail.com",
    "emailWork": "",
    "phone": "+7 747 597 24 48",
    "scopusId": "",
    "wosId": "",
    "orcid": "0009-0006-6716-9929"
  },
  {
    "id": "RauanB",
    "fullName": "Болатбек Рауан",
    "shortName": "RauanB",
    "dob": "2004-09-23",
    "position": "B st",
    "emailPersonal": "rauamtleu101@gmail.com",
    "emailWork": "bolatbek.r@edu.ektu.kz",
    "phone": "+7 776 482 36 63",
    "scopusId": "",
    "wosId": "",
    "orcid": "0009-0002-9613-3221"
  },
  {
    "id": "NurasylZh",
    "fullName": "Жасуланұлы Нұрасыл",
    "shortName": "NurasylZh",
    "dob": "2006-11-19",
    "position": "B st",
    "emailPersonal": "nurasylzhasulanuly@gmail.com",
    "emailWork": "zhasulanuly.n@edu.ektu.kz",
    "phone": "+7 706 603 53 33",
    "scopusId": "",
    "wosId": "",
    "orcid": ""
  }
];

window.PROJECTS_INITIAL = [
  {
    "id": "prj-pcfedm",
    "type": "ПЦФ-ЭДМ",
    "irn": "BR21882370",
    "title": "Разработка и внедрение технологии сверхзвуковой дуговой металлизации для упрочнения и восстановления деталей сельскохозяйственных машин",
    "period": "2023–2025",
    "manager": "Рахадилов Бауыржан Корабаевич",
    "totalFunding": 274728005,
    "contractKN": "",
    "contractInternal": "№172-579-23 от 15.11.2023",
    "procurement": 141348552,
    "services": 40031997,
    "partner": "ТОО «Институт композиционных материалов»"
  },
  {
    "id": "prj-gfkombi",
    "type": "ГФ-комби",
    "irn": "AP19680457",
    "title": "Разработка комбинированного способа обработки сферической головки имплантата тазобедренного сустава",
    "period": "2023–2025",
    "manager": "Узыерханова Гульназ Кенесхановна",
    "totalFunding": 96820480,
    "contractKN": "",
    "contractInternal": "",
    "procurement": 39824705,
    "services": 14790720,
    "partner": "ТОО «PlasmaScience»"
  },
  {
    "id": "prj-gftbp",
    "type": "ГФ термобарьерный",
    "irn": "AP23489951",
    "title": "Разработка комбинированного способа получения термобарьерного покрытия YSZ/GZO для теплонапряженных деталей и узлов изделий ракетно-космической техники",
    "period": "2024–2026",
    "manager": "Абдуллина Сауле Амангельдыевна",
    "totalFunding": 149454937,
    "contractKN": "№239/ГФ 24-26 от 09.09.2024",
    "contractInternal": "№146-576-24 от 09.09.2024",
    "procurement": 58415976,
    "services": 22996206,
    "partner": "ТОО «PlasmaScience»"
  },
  {
    "id": "prj-gfapp",
    "type": "ГФ аппликатор",
    "irn": "AP23489486",
    "title": "Повышение трибологических и коррозионных характеристик стальных инжекторов для внесения жидких удобрений в прикорневую зону",
    "period": "2024–2026",
    "manager": "Әділқанова Меруерт Әділқанқызы",
    "totalFunding": 142508493,
    "contractKN": "№239/ГФ 24-26 от 09.09.2024",
    "contractInternal": "№148-576-24 от 09.09.2024",
    "procurement": 71292795,
    "services": 18872600,
    "partner": "ТОО «PlasmaScience»"
  },
  {
    "id": "prj-pcf33",
    "type": "ПЦФ-33",
    "irn": "BR24992864",
    "title": "Создание оборудования и технологий обработки поверхностей деталей для металлообрабатывающей промышленности",
    "period": "2024–2026",
    "manager": "Баятанова Ляйла Болатхановна",
    "totalFunding": 348103373,
    "contractKN": "№383/ПЦФ 24-26 от 01.10.2024",
    "contractInternal": "№183-579-24 от 01.10.2024",
    "procurement": 156333564,
    "services": 72570313,
    "partner": "ТОО «Институт композиционных материалов»"
  },
  {
    "id": "prj-pcf90",
    "type": "ПЦФ-90",
    "irn": "BR24992862",
    "title": "Разработка инновационных технологий и новых материалов для создания отечественных медицинских имплантатов нового поколения",
    "period": "2024–2026",
    "manager": "Кенесбеков Айдар Бакытбекұлы",
    "totalFunding": 403665535,
    "contractKN": "№383/ПЦФ 24-26 от 01.10.2024",
    "contractInternal": "№184-607-24 от 01.10.2024",
    "procurement": 224542620,
    "services": 62357860,
    "partner": "ТОО «AYBALTA»"
  },
  {
    "id": "prj-mega",
    "type": "Мегагрант",
    "irn": "BR24992854",
    "title": "Разработка и реализация конкурентоспособных научно-обоснованных технологий для обеспечения устойчивого развития горно-металлургической отрасли Восточно-Казахстанской области",
    "period": "2024–2027",
    "manager": "Кокажметов Ернат Абилхайирович",
    "totalFunding": 759000000,
    "contractKN": "№437/ПЦФ 24-26 от 05.11.2024",
    "contractInternal": "",
    "procurement": 503896,
    "services": 96070,
    "partner": "ТОО «Институт композиционных материалов»"
  }
];

window.TASKS_INITIAL = [{"status":"!Focus","result":"Патент","who":"AinurS","deadline":"2026-04-30","direction":"ПЦФ-90","week":18},{"status":"!Focus","result":"Прайс лист с ценами на все УСО и оборудования","who":"AinurS","deadline":"2026-05-08","direction":"Center","week":19},{"status":"Done","result":"Тлеубек ага лаб фотолар","who":"AinurS","deadline":"2026-04-24","direction":"Center","week":17},{"status":"!Focus","result":"Дверь пластик 116 найти дверь или решение подогонать","who":"ArnurA","deadline":"2026-04-24","direction":"Center","week":17},{"status":"!Focus","result":"Замена стекла в 116 газотермия","who":"ArnurA","deadline":"2026-04-13","direction":"Center","week":16},{"status":"!Focus","result":"Эксперименты по МДО ","who":"ArnurA","deadline":"2026-04-24","direction":"ПЦФ-90","week":17},{"status":"!Focus","result":"Патент","who":"ArystanbekK","deadline":"2026-04-30","direction":"Мега","week":18},{"status":"!Focus","result":"статья скопус детонационное напыление покрытие","who":"ArystanbekK","deadline":"2026-04-24","direction":"ПЦФ-33","week":17},{"status":"!Focus","result":"Патент","who":"GulnaraZh","deadline":"2026-05-05","direction":"ПЦФ-33","week":19},{"status":"Done","result":"Конф СЗ МИНСК ","who":"GulnaraZh","deadline":"2026-04-17","direction":"ПЦФ-33","week":16},{"status":"!Focus","result":"Патентный поиск ","who":"GulnaraZh","deadline":"2026-04-30","direction":"ПЦФ-33","week":18},{"status":"!Focus","result":"Патент","who":"IndiraA","deadline":"2026-04-30","direction":"ПЦФ-33","week":18},{"status":"!Focus","result":"Исследование ВПН покрытия GZO ","who":"IndiraA","deadline":"2026-04-24","direction":"ГФ-ТБП","week":17},{"status":"!Focus","result":"Проект учета времени оборудования","who":"IndiraA","deadline":"2026-04-11","direction":"Center","week":15},{"status":"Done","result":"Написать статью","who":"MoldirK","deadline":"2026-04-17","direction":"Center","week":16},{"status":"!Focus","result":"Патент","who":"NurtoleuM","deadline":"2026-04-30","direction":"ПЦФ-33","week":18},{"status":"!Focus","result":"УСО- натурные испытания, инъекторы закуп","who":"NurtoleuM","deadline":"2026-04-24","direction":"ГФ-ИНЪ","week":17},{"status":"!Focus","result":"Воздух қосу, поключ. ион.","who":"RauanB","deadline":"2026-04-24","direction":"ПЦФ-90","week":17},{"status":"Done","result":"Магнетронка бойынша Ti-TiNO алу","who":"RauanB","deadline":"2026-04-24","direction":"ПЦФ-90","week":17},{"status":"!Focus","result":"Патент","who":"ZarinaA","deadline":"2026-05-05","direction":"Мега","week":19},{"status":"#Block","result":"Согласовать СЗ на отопление (117)","who":"ZarinaA","deadline":"2026-04-24","direction":"Center","week":17},{"status":"Done","result":"Отчет по губчатому титану","who":"ZarinaA","deadline":"2026-04-24","direction":"Мега","week":17},{"status":"Done","result":"Статья губчатый титан","who":"ZarinaA","deadline":"2026-04-22","direction":"Мега","week":17},{"status":".Inbox","result":"112 темыр балка ","who":"ArnurA","deadline":"2026-05-01","direction":"Center","week":18},{"status":".Inbox","result":"Купить отрезные диски для отрезных станков","who":"ArystanbekK","deadline":"2026-04-17","direction":"Center","week":16},{"status":".Inbox","result":"XRD дифрактометр отправить в китай через поставщика","who":"ArystanbekK","deadline":"2026-04-16","direction":"ГФ-ИНЪ","week":16},{"status":".Inbox","result":"Tekna сферодизация TiO2 порошка // Турция + РЭМ","who":"ArystanbekK","deadline":null,"direction":"Center","week":53},{"status":"Done","result":"ВПН покрытия GZO для термоциклического ","who":"IndiraA","deadline":"2026-04-17","direction":"ГФ-ТБП","week":16},{"status":".Inbox","result":"Заклеить кромку на большой стол","who":"NurasylZh","deadline":"2026-04-17","direction":"Center","week":16},{"status":"Done","result":"Напыление HVOF ","who":"YermakhanM","deadline":"2026-03-20","direction":"ГФ-ТБП","week":12},{"status":"Done","result":"Патент написать губчатый","who":"ZarinaA","deadline":"2026-03-30","direction":"Мега","week":14},{"status":"#Block","result":"КП ЭПО по мелочам","who":"ArystanbekK","deadline":"2026-04-03","direction":"ПЦФ-33","week":14},{"status":"#Block","result":"СЗ на оборудование ","who":"ZarinaA","deadline":"2026-04-17","direction":"ГФ-ИНЪ","week":16},{"status":"^Someday","result":"Наклейки на стекло по ВПН и ЭДМ 116","who":"ArystanbekK","deadline":null,"direction":"Center","week":53},{"status":"^Someday","result":"Бокс напыления установить провода, улучшение","who":"YermakhanM","deadline":null,"direction":"Center","week":53},{"status":"^Someday","result":"СЗ на приглашение Ауезхан Аманов","who":"ZarinaA","deadline":null,"direction":"Center","week":53},{"status":"Done","result":"Контент по направлениям НЦ для сайта - Порошковый, ГТН; тонкие пленки; модификация поверхности","who":"AinurS","deadline":"2026-04-17","direction":"Center","week":16},{"status":"Done","result":"Сайт закончить все по плану и заполнить контентом","who":"AinurS","deadline":"2026-04-17","direction":"Center","week":16},{"status":"Done","result":"Ремонт магнетронки - включить ВЧ и собрать, Ионник поставить ","who":"AinurS","deadline":"2026-04-10","direction":"ПЦФ-90","week":15},{"status":"Done","result":"Письмо ННС по ПЦФам статьи","who":"AinurS","deadline":"2026-04-10","direction":"ПЦФ-90","week":15},{"status":"Done","result":"отправить СЗ закуп раман, антивибрационный стол под Фишерскоуп ","who":"AinurS","deadline":"2026-03-31","direction":"ПЦФ-90","week":14},{"status":"Done","result":"Эксперимент с Лимарой агломерация","who":"AinurS","deadline":"2026-03-27","direction":"ПЦФ-90","week":13},{"status":"Done","result":"Патент отправить","who":"AinurS","deadline":"2026-03-14","direction":"ПЦФ-90","week":11},{"status":"Done","result":"Установить/купить/найти штапики для 116","who":"ArnurA","deadline":"2026-04-07","direction":"Center","week":15},{"status":"Done","result":"перевод и отправить статью","who":"ArnurA","deadline":"2026-04-06","direction":"ПЦФ-90","week":15},{"status":"Done","result":"Эксперимент губчатый титан","who":"ArnurA","deadline":"2026-04-03","direction":"Мега","week":14},{"status":"Done","result":"Установить стекло и заземление в 117","who":"ArnurA","deadline":"2026-03-27","direction":"Center","week":13},{"status":"Done","result":"Припаять теристоры к МДО","who":"ArnurA","deadline":"2026-03-13","direction":"ПЦФ-90","week":11},{"status":"Done","result":"Хоздоговор УМЗ РЭМ твердость","who":"ArystanbekK","deadline":"2026-04-17","direction":"Center","week":16},{"status":"Done","result":"Сферодизация хоздоговор","who":"ArystanbekK","deadline":"2026-04-10","direction":"Center","week":15},{"status":"Done","result":"КП по источнику питания на ЭПО Ибрагиму","who":"ArystanbekK","deadline":"2026-04-03","direction":"ПЦФ-33","week":14},{"status":"Done","result":"Tekna напыление TiN порошка (1 образец) // Айдар","who":"ArystanbekK","deadline":"2026-03-17","direction":"Center","week":12},{"status":"Done","result":"РЭМ Ернар водород","who":"ArystanbekK","deadline":"2026-03-13","direction":"Center","week":11},{"status":"Done","result":"Источник питания ЭПО митинг с Алмасбеком","who":"ArystanbekK","deadline":"2026-03-12","direction":"ПЦФ-33","week":11},{"status":"Done","result":"Переводы проектов на англ","who":"ArystanbekK","deadline":"2026-03-10","direction":null,"week":11},{"status":"Done","result":"Эксперимент по ЭПО 20Х","who":"GulnaraZh","deadline":"2026-04-17","direction":"ПЦФ-33","week":16},{"status":"Done","result":"Письмо ННС по ПЦФам статьи","who":"GulnaraZh","deadline":"2026-04-02","direction":"ПЦФ-33","week":14},{"status":"Done","result":"Найти квартиру для Евгении","who":"GulnaraZh","deadline":"2026-03-20","direction":"Center","week":12},{"status":"Done","result":"проверить отчеты по командировкам по всем проектам","who":"GulnaraZh","deadline":"2026-03-16","direction":"ПЦФ-33","week":12},{"status":"Done","result":"Отправить в журнал ККСОНВО ВКТУ с переводом","who":"GulnaraZh","deadline":"2026-03-11","direction":"ПЦФ-33","week":11},{"status":"Done","result":"Софинанс отчет + АВР","who":"GulnaraZh","deadline":"2026-03-10","direction":"ПЦФ-33","week":11},{"status":"Done","result":"Подготовка к Семинару неделя науки - организация","who":"IndiraA","deadline":"2026-04-01","direction":"Center","week":14},{"status":"Done","result":"ВПН покрытие GZO режим","who":"IndiraA","deadline":"2026-03-31","direction":"ГФ-ТБП","week":14},{"status":"Done","result":"Стенд для термоциклический план и чертеж","who":"IndiraA","deadline":"2026-03-20","direction":"ГФ-ТБП","week":12},{"status":"Done","result":"Твердость Мартенс покрытий после шлифовки","who":"IndiraA","deadline":"2026-03-18","direction":"ГФ-УТС","week":12},{"status":"Done","result":"оплата статьи СЗ ","who":"IndiraA","deadline":"2026-03-13","direction":"ГФ-ТБП","week":11},{"status":"Done","result":"Купить пистолеты воздушные для оборудований","who":"RauanB","deadline":"2026-03-26","direction":"Center","week":13},{"status":"Done","result":"Купить HDMI ","who":"RauanB","deadline":"2026-03-10","direction":"Center","week":11},{"status":"Done","result":"Стенд для термоциклический собрать","who":"YermakhanM","deadline":"2026-04-17","direction":"ГФ-ТБП","week":16},{"status":"Done","result":"Эксперимент ИПС спекание Айдар ага","who":"YermakhanM","deadline":"2026-04-07","direction":null,"week":15},{"status":"Done","result":"Подготовка к Семинару неделя науки - СММ инстаграм","who":"YermakhanM","deadline":"2026-04-01","direction":"Center","week":14},{"status":"Done","result":"Напыление HVOF WC-Co","who":"YermakhanM","deadline":"2026-03-28","direction":null,"week":13},{"status":"Done","result":"Сделать скрэтч как у Мерхата на покрытия WC-Co","who":"YermakhanM","deadline":"2026-03-17","direction":"ГФ-УТС","week":12},{"status":"Done","result":"Шлифовка образцов покрытий","who":"YermakhanM","deadline":"2026-03-17","direction":"ГФ-УТС","week":12},{"status":"Done","result":"Сделать скрэтч образцы Борисов","who":"YermakhanM","deadline":"2026-03-16","direction":"Center","week":12},{"status":"Done","result":"Купить и устнаовить кулер с водой в 116","who":"YermakhanM","deadline":"2026-03-06","direction":"Center","week":10},{"status":"Done","result":"Исследование губчатый титан","who":"ZarinaA","deadline":"2026-04-24","direction":"Мега","week":17},{"status":"Done","result":"з.7 - Трибология исследования для статьи ӘМӘ","who":"ZarinaA","deadline":"2026-04-17","direction":"ГФ-ИНЪ","week":16},{"status":"Done","result":"Рецензия статьи","who":"ZarinaA","deadline":"2026-04-17","direction":"ГФ-ИНЪ","week":16},{"status":"Done","result":"Оплата Евгения","who":"ZarinaA","deadline":"2026-04-10","direction":"Center","week":15},{"status":"Done","result":"Подготовка к Семинару неделя науки - выступают","who":"ZarinaA","deadline":"2026-04-01","direction":"Center","week":14},{"status":"Done","result":"з.7 - Трибология инъектор для статьи ӘМӘ","who":"ZarinaA","deadline":"2026-03-18","direction":"ГФ-ИНЪ","week":12},{"status":"Done","result":"Статья инъектор ИПА + мехобработка УНСМ","who":"ZarinaA","deadline":"2026-03-17","direction":"ГФ-ИНЪ","week":12},{"status":"Done","result":"Написать СЗ на проживание Евгения","who":"ZarinaA","deadline":"2026-03-17","direction":"Center","week":12},{"status":"Done","result":"Договор Евгения","who":"ZarinaA","deadline":"2026-03-13","direction":"Center","week":11},{"status":"Done","result":"СЗ на приглашение Евгении","who":"ZarinaA","deadline":"2026-03-11","direction":"Center","week":11},{"status":"Done","result":"Паспорт","who":"ZarinaA","deadline":null,"direction":"Мега","week":53},{"status":".Inbox","result":"Выполнить задачи Талап ага.","who":"ZarinaA","deadline":"2026-05-01","direction":"Center","week":18},{"status":"!Focus","result":"Собрать новости в СМИ с упоминанием PROFCOAT и дать список для сайта","who":"YermakhanM","deadline":"2026-05-15","direction":"Center","week":20},{"status":".Inbox","result":"Открыть почту profcoat@edu.ektu.kz","who":"MoldirK","deadline":"2026-05-15","direction":"Center","week":20}];
